(function(g){var window=this;var Z2=function(a){var b={languageCode:a.u,languageName:a.w,displayName:g.Az(a),kind:a.A,name:a.B,id:a.H,is_servable:a.D,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.C};a.o&&(b.translationLanguage=a.o);return b},$2=function(a){return a.o?a.o.languageCode:a.u},ipa=function(a,b){var c=new g.zz;
c.u=a.u;c.w=a.w;c.B=a.B;c.A=a.A;c.isDefault=!1;c.D=a.D;c.isTranslateable=a.isTranslateable;c.C=a.C;c.G=a.G;c.o=b;return c},jpa=function(){this.u=[];
this.o=[]},a3=function(a,b){return b?a.o.concat(a.u):a.o},b3=function(a,b){switch(b.A){case "asr":var c=a.u;
g.Va(c,(0,g.x)(b.Wq,b))||c.push(b);break;default:c=a.o,g.Va(c,(0,g.x)(b.Wq,b))||c.push(b)}},c3=function(a){g.A.call(this);
this.Ya=a;this.u=new jpa;this.B=[]},d3=function(a,b,c){c3.call(this,a);
this.o=null;this.B=b.Iu;this.w=c},e3=function(){this.o=[]},f3=function(a,b,c,d,e,f){g.A.call(this);
this.J=a;this.w=b;this.L=b.O();this.B=new e3;this.o=null;this.D=d;this.R=f;this.u=this.A=null;this.P=c;this.C=e||!1;this.G=new g.J(this.Rw,1E3,this);g.B(this,this.G);this.H=new g.R(this);g.B(this,this.H);this.H.M(b,"SEEK_COMPLETE",this.Lx);this.Lx();this.Rw()},g3=function(a,b){b-=a.w.tb();
var c=a.o;a.o=g.Ta(a.P.zf(b).o);c!=a.o&&a.R&&a.R()},h3=function(a,b){var c=g.lw(g.By(b,a.J,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.Np(c,d,3,100).then((0,g.x)(a.nL,a));a.A=b;c=a.B;d=a.A.o[0].u;var e=g.lb(c.o,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.o[e-1]&&e<c.o.length&&1==c.o[e]-d?(g.ab(c.o,e),g.ab(c.o,e-1)):0<e&&1==d-c.o[e-1]?c.o[e-1]=d:e<c.o.length&&1==c.o[e]-d?c.o[e]=d:(g.ib(c.o,e,0,d),g.ib(c.o,e+1,0,d)))},i3=function(a,b){c3.call(this,b.O());
this.o=a;this.D=b;this.w=null;this.A=!1;this.C=g.hy(this.D.O())&&!this.o.u},j3=function(a,b){var c=[],d;
for(d in a.o.o){var e=a.o.o[d];if(g.GQ(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.zz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},kpa=function(a,b){return null!=b&&b in a.o.o?a.o.o[b]:null},k3=function(a,b,c){var d=[],e;
for(e in a.o.o){var f=a.o.o[e];if(g.GQ(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},l3=function(a,b,c,d,e){c3.call(this,e||null);
c=c||g.Wo(a).hl||"";c=c.split("_").join("-");this.A=g.Yo(a,{hl:c});this.w=b;this.C=!!d;this.D={};this.o=null},m3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.iF.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.w=f;this.o=k},n3=function(a,b,c,d,e){g.iF.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},p3=function(a){a=void 0===a?{}:a;
var b="_"+o3++;return new n3(0,0x8000000000000,0,b,a)},r3=function(a,b,c,d,e,f){var k={};
g.Pa(k,b);g.Pa(k,a.params);g.Pa(k,c);var l={};g.Pa(l,b.vb);a.params.vb&&g.Pa(l,a.params.vb);g.Pa(l,c.vb);k.vb=l;g.X.call(this,{F:"div",I:"caption-window",N:{id:"caption-window-"+a.id,dir:1==k.te?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},K:[{F:"span",I:"captions-text",N:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.U=!1;this.A=a;this.aa=this.V=null;this.La=e;this.Ja=f;this.G=null;this.ba=.96*e;this.xa=.96*f;this.w=k;this.Ga=c;this.C=this.u["captions-text"];this.Aa=
null!=this.C.style["box-decoration-break"]||null!=this.C.style["-webkit-box-decoration-break"];this.Z=d/360*16;this.type=0;this.la=this.Z*q3(l);a=new g.IM(this.element,!0);g.B(this,a);a.subscribe("dragstart",this.AG,this);a.subscribe("dragmove",this.zG,this);a.subscribe("dragend",this.yG,this);this.wa=this.oa=0;b="";this.w.windowOpacity&&(a=g.V_(this.w.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.w.windowOpacity+")");a={"background-color":b,display:!1===this.w.isVisible?"none":"","text-align":lpa[this.w.textAlign]};
this.Aa&&(a["border-radius"]=b?this.la/8+"px":"");if(this.B=2==this.A.params.te||3==this.A.params.te)b=this.element,c="vertical-rl",1==this.w.JA&&(c="vertical-lr"),g.Ed&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.kh(b,"-o-writing-mode",c),g.kh(b,"-webkit-writing-mode",c),g.kh(b,"writing-mode",c),g.kh(b,"text-orientation","upright"),g.L(b,"ytp-vertical-caption"),3==this.A.params.te&&(g.kh(b,"text-orientation",""),g.kh(b,"transform","rotate(180deg)"));g.kh(this.element,a);switch(this.w.Wf){case 0:case 1:case 2:g.L(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.L(this.element,"ytp-caption-window-bottom")}},q3=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},s3=function(a,b){var c={},d=b.background?b.background:a.w.vb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.w.vb.backgroundOpacity;d=g.V_(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Aa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.la/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*q3(b)+"px";d=1;e=b.color||a.w.vb.color;if(b.color||null!=b.textOpacity)e=g.V_(e),d=null==b.textOpacity?a.w.vb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Qu&&(k=e=b.Qu);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=t;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.xp()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.w.vb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Oe&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.nE&&(c.visibility="hidden");1==b.pE&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.jy||g.ky,3==a.A.params.te?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.se||2==b.se||3==b.se||4==b.se||5==b.se)if(g.jy)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.se){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},t3=function(a){a.G=g.Ld("SPAN");
g.kh(a.G,{display:"block"});g.L(a.G,"caption-visual-line");a.C.appendChild(a.G)},u3=function(a,b){var c=g.Ld("SPAN");
g.kh(c,{display:"inline-block","white-space":"pre-wrap"});g.kh(c,s3(a,b));c.classList.add("ytp-caption-segment");a.G.appendChild(c);c.previousElementSibling&&(g.kh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.kh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},v3=function(a,b,c){a.U=a.U||!!c;
var d={};g.Pa(d,a.w.vb);g.Pa(d,c||b.o);g.Pa(d,a.Ga.vb);(c=!a.G)&&t3(a);for(var e=a.V&&a.aa&&g.Yb(d,a.aa)?a.V:u3(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.w,n=k[l];m&&!c?(t3(a),e=u3(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Md(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.jy||!g.oh(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.oh(n.children[2],"text-emphasis-position")&&(m=a.B?"padding-left":"padding-bottom"),g.Gd?
g.kh(e,m,"1em"):g.kh(e,m,"0.5em")))}a.aa=d;a.V=e;a.D.push(b)},w3=function(){},y3=function(){this.A=this.u=this.mode=this.w=0;
this.B=new x3(this);this.C=new x3(this);this.o=[];this.clear()},mpa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Cl:a,
Dl:b,result:0};a=z3[a];b=z3[b];if(a&128){if(!(b&128)&&0!=c.o&&c.u==b)return{Cl:a,Dl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Cl:a,Dl:b,result:2};return{Cl:a,Dl:b,result:3}},npa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,A3(a.B,b,c,d))},opa=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.u=d.time;0==d.type?npa(a,d.Ku,d.Lu,b):1==d.type&&a.w&496&&A3(a.C,d.Ku,d.Lu,b)}a.o.length=0},B3=function(){this.o=0},C3=function(){this.u=this.w=this.o=0},D3=function(){this.timestamp=this.Wd=0},E3=function(a){this.w=[];
for(var b=0;15>=b;b++){this.w[b]=[];for(var c=0;32>=c;c++)this.w[b][c]=new D3}this.o=this.u=this.row=0;this.style=new B3;this.B=a;this.A=0},F3=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.B.u+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.w[m][q];
if(0!=t.Wd){0==c&&(c=m,d=q);n=String.fromCharCode(t.Wd);var v=t.timestamp;v<e&&(e=v);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.Wd||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.u+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.w[k][m],t=q.Wd,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),v=q.timestamp,v<=e&&(e=v),l+=n,q.reset()),32==m||0==t)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},tpa=function(a,b){switch(a){case 0:return ppa[(b&127)-32];
case 1:return qpa[b&15];case 2:return rpa[b&31];case 3:return spa[b&31]}return 0},G3=function(a){return a.w[a.row][a.u]},H3=function(a,b,c){2<=b&&1<a.u&&(--a.u,G3(a).Wd=0);
var d=G3(a);d.timestamp=a.B.u+0;d.Wd=tpa(b,c);32>a.u&&a.u++},I3=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.w[b+e][f].cg(a.w[c+e][f])},J3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.w[b+d][e].reset()},K3=function(a){a.row=0<a.o?a.o:1;
a.u=1;J3(a,0,15)},L3=function(a){this.A=a;
this.B=0;this.style=new B3;this.C=new E3(a);this.D=new E3(a);this.G=new E3(a);this.u=this.C;this.w=this.D;this.o=this.u},M3=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:F3(d,c),K3(a.u),K3(a.w),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.A;e?d.u=1:d.o!=b&&(d.o>b?(F3(d,c),J3(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},N3=function(a){a.style.set(1);
a.o=a.w;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.A},O3=function(a){a.style.set(4);
a.o=a.G;a.o.style=a.style;a.A.mode=1<<a.o.A},x3=function(a){this.u=a;
this.o=new C3;this.B=0;this.w=new L3(a);this.C=new L3(a);this.A=this.w},A3=function(a,b,c,d){a.o.update();
b=mpa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Cl;c=b.Dl;if(32<=e||!e)a.u.mode&a.u.w&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.o,b&96&&H3(a,0,b),c&96&&H3(a,0,c),0!=b&&0!=c&&3==a.style.o&&F3(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.w=e,b.u=c,b.o=2,b=e&8?a.C:a.w,a.A=b,a.u.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.o?1:0),(a.u.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.o?1:0))&a.u.w))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;I3(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));J3(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:H3(b.o,0,32);break a;case 48:57==c?(d=b.o,G3(d).Wd=0,32>d.u&&d.u++):H3(b.o,1,c&15)}break;case 2:c&32&&H3(b.o,2,c&31);break;case 3:c&32&&H3(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:N3(b);break;case 33:d=
b.o;1<d.u&&(--d.u,G3(d).Wd=0);break;case 36:d=b.o;b=G3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.w[a][c]==b){for(;32>=c;c++)d.w[a][c].reset();break}break;case 37:M3(b,2,d);break;case 38:M3(b,3,d);break;case 39:M3(b,4,d);break;case 40:H3(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.A;break;case 42:d=b.G;d.o=15;d.style.set(4);K3(d);O3(b);break;case 43:O3(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:F3(a,d)}J3(a,0,15);break;case 45:b:{a=
b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;F3(a,d);I3(a,b,b+1,a.o-1);J3(a,a.row,1)}break;case 46:J3(b.w,0,15);break;case 47:F3(b.u,d),b.w.updateTime(b.A.u+0),d=b.w,b.w=b.u,b.u=d,N3(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},P3=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.cd){var n=f[1],q=f[2],t=f[3];l.getAttribute("p");var v=g.xp();l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");t.getAttribute("t");f=v?g.Ld("DIV"):g.Ld("RUBY");l=l.textContent;var z=g.Ld("SPAN");z.textContent=l;f.appendChild(z);n.getAttribute("p");z=v?g.Ld("DIV"):g.Ld("RP");l=n.textContent;z.textContent=l;f.appendChild(z);k=k[q.getAttribute("p")];l=q.textContent;q=v?g.Ld("DIV"):g.Ld("RT");q.textContent=l;f.appendChild(q);l=k.cd;if(10==l||11==l||12==l||13==l||14==l)if(g.kh(q,"text-emphasis-style",
"filled circle"),g.kh(q,"text-emphasis-color","currentcolor"),g.kh(q,"webkit-text-emphasis","filled circle"),k.cd==k.cd==11||13==k.cd)g.kh(q,"webkit-text-emphasis-position","under left"),g.kh(q,"text-emphasis-position","under left");q=!0;if(4==k.cd||7==k.cd||12==k.cd||14==k.cd)g.kh(f,"ruby-position","over"),g.kh(f,"-webkit-ruby-position","before");else if(5==k.cd||6==k.cd||11==k.cd||13==k.cd)g.kh(f,"ruby-position","under"),g.kh(f,"-webkit-ruby-position","after"),q=!1;t.getAttribute("p");l=t.textContent;
t=v?g.Ld("DIV"):g.Ld("RP");t.textContent=l;f.appendChild(t);v&&(v=q,g.kh(f,{display:"inline-block",position:"relative"}),t=f.firstElementChild.nextElementSibling,g.kh(t,"display","none"),t=t.nextElementSibling,g.kh(t,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.kh(f.lastElementChild,"display","none"),v?(g.kh(f,"padding-top","0.6em"),g.kh(t,"top","0")):(g.kh(f,"padding-bottom","0.6em"),g.kh(t,"bottom",
"0")));return new m3(a,b,e,c,f,d,m)}switch(m.cd){case 9:case 10:m.se=1;break;case 11:m.se=2;break;case 12:m.se=3;break;case 13:m.se=4;break;case 14:m.se=5}return new m3(a,b,e,c,l.textContent||"",d,m)},Q3=function(){g.A.apply(this,arguments)},R3=function(a){Q3.call(this);
this.w={};this.H={};this.J={};this.B="_"+o3++;this.C=a;this.G={};this.u=this.o=null;this.D=!0},S3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},T3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},U3=function(a,b){var c=S3(a,b);
return void 0!=c?c:null},W3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return V3.test(c),c},X3=function(a,b){var c={},d=b.getAttribute("ws");
g.Pa(c,d?a.J[d]:a.C);d=U3(b,"mh");null!=d&&(c.Oq=d);d=U3(b,"ju");null!=d&&(c.textAlign=d);d=U3(b,"pd");null!=d&&(c.te=d);d=U3(b,"sd");null!=d&&(c.JA=d);d=W3(b,"wfc");null!=d&&(c.windowColor=d);d=S3(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},Y3=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Pa(c,a.H[d]);d=U3(b,"ap");null!=d&&(c.Wf=d);d=S3(b,"cc");null!=d&&(c.Ql=d);d=S3(b,"ah");null!=d&&(c.Pe=d);d=S3(b,"rc");null!=d&&(c.Jk=d);d=S3(b,"av");null!=d&&(c.Ig=d);return c},Z3=function(a,b,c,d){var e={};
g.Pa(e,Y3(a,b));g.Pa(e,X3(a,b));d?g.Yb(e,a.C)?(d=a.B,e=a.C):d="_"+o3++:d=b.getAttribute("id")||"_"+o3++;a=S3(b,"t")+c;b=S3(b,"d")||0x8000000000000;if(2==e.te||3==e.te)c=e.Jk,e.Jk=e.Ql,e.Ql=c;return new n3(a,b,0,d,e)},$3=function(a,b,c,d,e,f,k){r3.call(this,a,b,c,d,e,f,k);
this.type=1},a4=function(a,b,c){this.D=c;
this.version=this.C=this.A=this.o=0;this.u=new DataView(a);this.w=[]},b4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},c4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},d4=function(a,b){Q3.call(this);
this.u=a;this.track="CC3"==b.w?4:0;this.o=new y3;this.o.w=1<<this.track},f4=function(a){if("string"===typeof a)return!1;
a=new a4(a,8,0);return e4(a)},e4=function(a){if(!(a.o<a.u.byteLength)||1380139777!=c4(a))return!1;
a.version=b4(a);if(1<a.version)return!1;b4(a);b4(a);b4(a);return!0},g4=function(a,b,c,d,e,f,k){r3.call(this,a,b,c,d,e,f,k);
g.L(this.element,"ytp-caption-window-rollup");this.type=2;this.H=[];this.L=this.J=this.ga=0;this.P=NaN;this.ya=0;this.Ba=null;this.fa=new g.J(this.sL,433,this);g.B(this,this.fa);g.kh(this.element,"overflow","hidden")},upa=function(a,b){return(a.B?b.offsetHeight:b.offsetWidth)+1},vpa=function(a){if(isNaN(a.P)){var b=a.w.Ql;
if(b){var c=g.Ld("SPAN");g.Vd(c,"\u2013".repeat(b));g.kh(c,s3(a,a.w.vb));a.C.appendChild(c);a.P=c.offsetWidth;a.C.removeChild(c)}else a.P=0}return a.P},wpa=function(a,b){if(!b)return"";
a.B&&1!=a.A.params.JA&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},h4=function(a){a.H=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.A.params.Jk,c=0,d=0,e=a.H.length-1;c<b&&-1<e;){var f=a.H[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.H.length<b&&(d*=b/a.H.length);a.J=d;a.L=Math.max(vpa(a),a.ya,upa(a,a.C))},xpa=function(a,b){h4(a);
var c=a.H.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.J-c;if(c!=a.ga){var d=0<c&&0==a.ga;b||isNaN(c)||d||(g.L(a.element,"ytp-rollup-mode"),g.Tm(a.fa));g.kh(a.C,"transform",wpa(a,c));a.ga=c}h4(a)},i4=function(){Q3.call(this)},j4=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Oe=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType){q=new m3(b,c,d,e.id,q.nodeValue,f||0<n,g.Wb(l)?void 0:l);m.push(q);var t=e;g.B(t,q);t.o.push(q)}else t={},g.Pa(t,l),j4(a,b,c,d,e,!0,q,t,m)}},k4=function(a){var b=a.split(":");
a=0;b=g.p(b);for(var c=b.next();!c.done;c=b.next())a=60*a+parseFloat(c.value);return 1E3*a},l4=function(a,b,c,d){d=Object.assign({Oq:0},d);
return new n3(a,b,c,"_"+o3++,d)},m4=function(a){g.A.call(this);
this.u=a;this.o=null},p4=function(a){g.FQ.call(this,a);
this.w=a.O();this.T=a.getVideoData();this.wa=g.YK(a);this.U=a;var b=null,c=g.In("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.sn(c));this.aa=b;this.A={vb:{}};this.C={vb:{}};this.J=[];this.L={};this.da={};this.R=!1;this.la=g.HQ(this.T,this.U);this.xa=!!this.T.captionTracks.length;this.ya=!!this.T.rj;this.ga="3"==this.w.controlsType;b=a.app.B;c=!(!b||!b.Xk());this.oa=!(!b||!b.Kh());this.B=this.ga&&c&&!this.la;this.H=!this.B&&this.ga&&this.oa&&this.la;this.u=this.D=this.G=this.V=this.fa=
null;this.Z=new m4(this.w);g.B(this,this.Z);c=b=this.o=null;this.B||(b=new g.Qm(this.cB,void 0,this),g.B(this,b),c=new g.J(this.WM,2E3,this),g.B(this,c));this.ba=b;this.ra=c;this.P=new g.R(this);g.B(this,this.P);this.B||this.P.M(a,"resize",this.mt);this.P.M(a,"onPlaybackAudioChange",this.XI);this.P.M(a,g.lF("captions"),this.yF,this);this.P.M(a,"crx_captions",this.zF,this);n4(this,o4(this,"display-settings")||{})},q4=function(a){if(1==a.w.Zf||1==a.T.Zf||"alwayson"==g.zC(a.T,"yt:cc"))return!0;
if(2==a.w.Zf){var b=o4(a,"module-enabled");if(null!=b)return!!b}if(a.T.captionTracks.length)var c=a.player.getAudioTrack().lp;return"ON"==c||"on"==g.zC(a.T,"yt:cc")},r4=function(a,b){if(a.o&&(void 0===b||!b)||!a.T.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.gm||"FORCED_ON"==c.lp},t4=function(a,b){if(a.u){if(a.D&&a.D.o)return a.D.o;
var c=b;c||(c=a.ya?!1:a.xa?!1:!0);c=a3(a.u.u,c);for(var d=[a.T.captionsLanguagePreference,a.w.captionsLanguagePreference,g.zC(a.T,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if($2(c[f])==d[e])return c[f];return a.D&&a.D.xp?a.D.xp:(d=c.find(function(k){return k.isDefault}))?d:c[0]||s4(a)}return null},s4=function(a){return a.D&&a.D.gm},u4=function(a){var b=s4(a);
return!!b&&a.o==b},v4=function(a,b){for(var c=a.U.app.B.Za().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},x4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.R=c,a.R&&w4(a,"module-enabled",!!b));a.o=b;r4(a)&&(a.o=s4(a));a.load()},ypa=function(a,b){var c=a.wa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.wa.getPlayerSize();switch(null!=b.params.Oq?b.params.Oq:1<b.o.length?1:0){case 1:return new $3(b,a.A,a.C,c,d.width,d.height,a.w.experiments);case 2:return new g4(b,a.A,a.C,c,d.width,d.height,a.w.experiments);default:return new r3(b,a.A,a.C,c,d.width,d.height,a.w.experiments)}},n4=function(a,b,c){var d=y4.vb;
a.A={};g.Pa(a.A,y4);a.A.vb={};g.Pa(a.A.vb,d);a.C={vb:{}};var e=b.backgroundOverride?a.C:a.A,f=b.background||d.background;V3.test(f);e.vb.background=f;e=b.colorOverride?a.C:a.A;f=b.color||d.color;V3.test(f);e.vb.color=f;e=b.windowColorOverride?a.C:a.A;f=b.windowColor||y4.windowColor;V3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.A;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.vb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.A;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.vb.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.A;e=b.fontStyle;null==e&&(e=d.bold&&d.Oe?3:d.bold?1:d.Oe?2:0);f=f.vb;switch(e){case 1:f.bold=!0;delete f.Oe;break;case 2:delete f.bold;f.Oe=!0;break;case 3:f.bold=!0;f.Oe=!0;break;default:delete f.bold,delete f.Oe}e=b.textOpacityOverride?a.C:a.A;f=b.textOpacity;null==f&&(f=d.textOpacity);e.vb.textOpacity=f;e=b.windowOpacityOverride?a.C:a.A;f=b.windowOpacity;null==f&&(f=y4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.C:a.A;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.vb.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.A;f=b.fontFamily;null==f&&(f=d.fontFamily);e.vb.fontFamily=f;a.loaded&&a.mt();c&&w4(a,"display-settings",b)},A4=function(a,b){if(b&&!a.G){var c=p3({te:0,
lang:"tr"});a.G=[c,new m3(c.start,c.end-c.start,0,c.id,"Altyaz\u0131lar \u015fu \u015fekilde g\u00f6r\u00fcn\u00fcr")];g.lL(a.player,a.G)}else!b&&a.G&&(z4(a,a.G),a.G=null)},z4=function(a,b){g.wU(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.bb(this.J,c)},a);
a.ba.hi()},o4=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},w4=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.zz.prototype.Wq=g.ca(11,function(a){return a?this.toString()==a.toString():!1});
g.tu.prototype.tm=g.ca(10,function(a){return(a=this.fg(a))?a.o:0});
g.Ty.prototype.tm=g.ca(9,function(){return 0});
g.vt.prototype.sj=g.ca(8,function(){for(var a=g.xd(document,"track",void 0,this.o),b=0;b<a.length;b++)g.Qd(a[b])});
g.vS.prototype.sj=g.ca(7,function(){this.o.sj()});
g.vt.prototype.Xk=g.ca(6,function(){return!!this.o.textTracks});
g.vS.prototype.Xk=g.ca(5,function(){return this.o.Xk()});
g.vt.prototype.nj=g.ca(4,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.vS.prototype.nj=g.ca(3,function(a){this.o.nj(a)});
g.lt.prototype.Kh=g.ca(2,function(){});
g.vt.prototype.Kh=g.ca(1,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.vS.prototype.Kh=g.ca(0,function(){return this.o.Kh()});
var zpa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,V3=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(c3,g.A);c3.prototype.Gz=function(){return!1};
c3.prototype.Y=function(){this.Jg();g.A.prototype.Y.call(this)};
g.r(d3,c3);d3.prototype.Mq=function(a,b,c){b=this.Jj(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Jg();this.o=g.op(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
d3.prototype.Nq=function(a){if(this.w)for(var b=g.p(this.w.captionTracks),c=b.next();!c.done;c=b.next())b3(this.u,c.value);a()};
d3.prototype.Jj=function(a,b){var c=a.G,d={fmt:b};if("srv3"==b||"3"==b)g.xp()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.o&&(d.tlang=$2(a));return g.Yo(c,d)};
d3.prototype.Jg=function(){this.o&&this.o.abort()};
e3.prototype.contains=function(a){a=g.lb(this.o,a);return 0<=a||0>a&&1==(-a-1)%2};
e3.prototype.length=function(){return this.o.length/2};
g.r(f3,g.A);g.h=f3.prototype;g.h.Y=function(){g.A.prototype.Y.call(this);this.u&&this.u.cancel()};
g.h.Lx=function(){g3(this,this.w.getCurrentTime())};
g.h.reset=function(){this.B=new e3;this.u&&(this.u.cancel(),this.u=null)};
g.h.Rw=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.Kf(a);!a||this.u||this.o&&30<this.o.startTime-this.w.getCurrentTime()||(a=this.o,a=a.o.Ci(a),a.o[0].duration?(this.B.contains(a.o[0].u)||h3(this,a),this.o=g.Ta(a.o)):!g.S(this.L.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.B&&this.o.B+this.w.tb()<this.w.getCurrentTime()&&g3(this,this.w.getCurrentTime()));this.G.start()};
g.h.nL=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.Yy(a);c?(a=g.By(this.A,this.J,{}),b=this.A,g.wy(b.u,a,c),b.requestId=a.get("req_id"),h3(this,this.A)):(b||null===this.D||(c=this.A.o[0],this.C?this.D(a.response,1E3*(c.startTime+this.w.tb())):this.D(a.responseText,1E3*(c.startTime+this.w.tb()))),this.u=this.A=null)};
g.r(i3,c3);g.h=i3.prototype;g.h.Mq=function(a,b,c){this.Jg();b=kpa(this,a.getId());b||(b=a.u,b=this.o.u?k3(this,b,"386"):k3(this,b));if(b){var d=1E3*(b.index.tm(b.index.me())-b.index.Mc(b.index.me()));this.w=new f3(new g.ry,this.D,b,function(e,f){c(e,a,f,d)},this.C||g.As(b.info),(0,g.x)(function(){this.w&&this.w.reset();
this.A=!0},this))}};
g.h.Gz=function(){var a=this.A;this.A=!1;return a};
g.h.Nq=function(a){var b;this.C?b=[new g.zz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.zz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.o.u?j3(this,"386"):j3(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())b3(this.u,c.value);a()};
g.h.Jg=function(){this.w&&(this.w.dispose(),this.w=null)};
g.h.Jj=function(){return""};
g.r(l3,c3);l3.prototype.Mq=function(a,b,c){b=this.Jj(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Jg();this.o=g.op(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
l3.prototype.Nq=function(a){var b=this.A,c={type:"list",tlangs:1,v:this.w,vssids:1};this.C&&(c.asrs=1);b=g.Yo(b,c);c=(0,g.x)(function(d){this.o=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.p(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),q=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),v="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
b3(this.u,new g.zz({languageCode:f,languageName:l,name:m,kind:n,id:q,is_servable:!0,is_translateable:v,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),q=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:q,isDefault:t},this.D[l.languageCode]=l.languageName,this.B.push(l)}a()},this);
this.Jg();this.o=g.op(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
l3.prototype.Jj=function(a,b){var c=this.A,d={v:this.w,type:"track",lang:a.u,name:a.getName(),kind:a.A,fmt:b};a.o&&(d.tlang=$2(a));return c=g.Yo(c,d)};
l3.prototype.Jg=function(){this.o&&this.o.abort()};var lpa=["left","right","center","justify"];var y4={windowColor:"#080808",windowOpacity:0,textAlign:2,Wf:7,Pe:50,Ig:100,vb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(m3,g.iF);m3.prototype.toString=function(){return g.iF.prototype.toString.call(this)};g.r(n3,g.iF);n3.prototype.toString=function(){return g.iF.prototype.toString.call(this)};
var o3=0;g.r(r3,g.X);g.h=r3.prototype;g.h.AG=function(a,b){var c=g.Bh(this.element,this.element.parentElement);this.oa=a-c.x;this.wa=b-c.y;g.L(this.element,"ytp-dragging")};
g.h.zG=function(a,b){var c=g.Eh(this.element),d=a-this.oa-.02*this.La,e=b-this.wa-.02*this.Ja,f=(d+c.width/2)/this.ba*3;f=Math.floor(g.kd(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.kd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ba;d=100*g.kd(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.kd(c,0,1);this.A.params.Wf=l;this.A.params.Ig=c;this.A.params.Pe=d;this.w.Wf=l;this.w.Ig=c;this.w.Pe=d;this.gA()};
g.h.yG=function(){g.dn(this.element,"ytp-dragging")};
g.h.gA=function(){this.Hh(this.D)};
g.h.Hh=function(a){var b=Math.min(this.Kv(),this.ba),c=this.Jv(),d="";3==this.A.params.te&&(d="rotate(180deg)");g.kh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Zo(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.w.Pe+2;d=this.w.Wf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.w.Ig+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.kh(this.element,a)};
g.h.Zo=function(a){var b;for(b=0;b<a.length&&a[b]==this.D[b];b++);if(this.U||this.D.length>b)b=0,this.U=!1,this.D=[],this.G=this.aa=this.V=null,g.Od(this.C);for(;b<a.length;b++)v3(this,a[b])};
g.h.Kv=function(){return 0};
g.h.Jv=function(){return 0};
g.h.toString=function(){return g.X.prototype.toString.call(this)};w3.prototype.B=function(){};y3.prototype.clear=function(){this.A=this.u=this.mode=0;this.o=[];this.reset()};
y3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var z3=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];B3.prototype.set=function(a){this.o=a};
B3.prototype.get=function(){return this.o};
C3.prototype.clear=function(){this.o=0};
C3.prototype.update=function(){this.o=2==this.o?1:0};
C3.prototype.matches=function(a,b){return 0!=this.o&&a==this.w&&b==this.u};
D3.prototype.cg=function(a){this.Wd=a.Wd;this.timestamp=a.timestamp};
D3.prototype.reset=function(){this.timestamp=this.Wd=0};
E3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.w[b][c].timestamp=a};
E3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.w[b][c];a=0==d.Wd?a+"_":a+String.fromCharCode(d.Wd)}a+="\n"}return a};
E3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.w[b][c].reset();this.A=a;this.o=0;this.u=this.row=1};
var ppa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],qpa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],rpa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],spa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];L3.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.u=this.C;this.w=this.D;this.o=this.u;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
x3.prototype.reset=function(a){this.B=a;this.o.clear();this.A=this.w;this.w.reset(a,0);this.C.reset(a,1)};g.r(Q3,g.A);Q3.prototype.reset=function(){};g.r(R3,Q3);R3.prototype.reset=function(){this.G={};this.u=this.o=null;this.D=!0};
R3.prototype.A=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.w,l={},m=c.getAttribute("p");m&&g.Pa(l,this.w[m]);m=T3(c,"b");null!=m&&(l.bold=
m);m=T3(c,"i");null!=m&&(l.Oe=m);m=T3(c,"u");null!=m&&(l.underline=m);m=U3(c,"et");null!=m&&(l.charEdgeStyle=m);m=U3(c,"of");null!=m&&(l.offset=m);m=W3(c,"bc");null!=m&&(l.background=m);m=W3(c,"ec");null!=m&&(l.Qu=m);m=W3(c,"fc");null!=m&&(l.color=m);m=U3(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=S3(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=S3(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=S3(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=U3(c,"rb");null!=m&&10!=m&&0!=m&&(l.cd=10<m?m-1:m);
m=U3(c,"hg");null!=m&&(l.pE=m);c=U3(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.se=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.J[d]=X3(this,c);break;case "wp":d=c.getAttribute("id"),this.H[d]=Y3(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=Z3(this,d,e,!1);g.B(this,this.o);(d=this.G[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.G[this.o.id]=this.o;c.push(this.o);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.B;m=!!T3(d,"a");n=(S3(d,"t")||0)+n;var q=S3(d,"d")||5E3;m||(!this.D&&this.u&&this.u.windowId==l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"==this.u.text&&(this.u.text=""));var t=m?6:5,v=this.w[d.getAttribute("p")],z=[].concat(g.ea(d.childNodes));z.length&&(this.D=null!=d.getAttribute("d"));for(var C=0;C<z.length;C++){var D=z[C],G=void 0;0<C&&(m=!0);var K=void 0;1==D.nodeType&&(K=D);if(K&&"s"==K.tagName){if((D=this.w[K.getAttribute("p")])&&D.cd&&(1==D.cd?(D=z.slice(C,
C+4),4==D.length&&(G=P3(n,q,l,m,t,D,this.w),C+=3)):G=P3(n,q,l,m,t,[K],this.w)),!G){var F=K;G=n;K=q;D=l;var M=m,ka=t,na=F.textContent?F.textContent:"",Ha=this.w[F.getAttribute("p")];F=S3(F,"t")||0;G=new m3(G+F,K-F,ka,D,na,M,Ha)}}else G=new m3(n,q,t,l,D.textContent||"",m,v);k.push(G);this.u=G}if(0<k.length)for(k[0].windowId==this.B&&(this.o=Z3(this,d,e,!0),g.B(this,this.o),c.push(this.o)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,l=this.o,g.B(l,k),l.o.push(k),c.push(k)}e=
c}else e=[];return e};g.r($3,r3);$3.prototype.Zo=function(a){var b=this.A.o;r3.prototype.Zo.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Pa(d,c.o);g.Pa(d,Apa);var e=c.o;var f=d}v3(this,c,d)}};
var Apa={nE:!0};g.r(a4,w3);a4.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+o3++;c=c/1E3-this.D;d=d/1E3-this.D;a=new n3(c,d-c,5,f,{textAlign:0,Wf:0,Pe:2.5*b,Ig:5.33*a});e=new m3(c,d-c,5,f,e);this.w.push(a);this.w.push(e)}};
g.r(d4,Q3);d4.prototype.A=function(a){a=new a4(a,a.byteLength,this.u);if(e4(a)){for(;a.o<a.u.byteLength;)for(0==a.version?a.A=c4(a)*(1E3/45):1==a.version&&(a.A=4294967296*c4(a)+c4(a)),a.C=b4(a);0<a.C;a.C--){var b=b4(a),c=b4(a),d=b4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.A,type:this.track,Ku:c,Lu:d,order:b.o.length}))}opa(this.o,a);return a.w}return[]};
d4.prototype.reset=function(){this.o.clear()};g.r(g4,r3);g.h=g4.prototype;g.h.gA=function(){g.Um(this.fa)};
g.h.sL=function(){g.dn(this.element,"ytp-rollup-mode");this.Hh(this.Ba,!0)};
g.h.Jv=function(){return this.B?this.L:this.J};
g.h.Kv=function(){return this.B?this.J:this.L};
g.h.Hh=function(a,b){this.Ba=a;if(this.A.params.Jk){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.ya=this.L;this.J=this.L=0;r3.prototype.Hh.call(this,a);xpa(this,b);r3.prototype.Hh.call(this,a)}else r3.prototype.Hh.call(this,a)};g.r(i4,Q3);
i4.prototype.A=function(a,b){for(var c=[],d=a.split(Bpa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Cpa.test(f)){var l=B4.exec(f);if(l&&4<=l.length){var m=k4(l[1]),n=k4(l[2])-m;m+=k;var q,t=q=void 0,v=void 0,z=void 0,C=(l=l[3])?l.split(" "):[];l={textAlign:2};C=g.p(C);for(var D=C.next();!D.done;D=C.next())if(D=D.value.split(":"),2==D.length){var G=D[1];switch(D[0]){case "line":D=G.split(",");D[0].endsWith("%")&&(z=D[0],l.Ig=Number.parseInt(z,10),2==D.length&&(v=D[1].trim()));break;case "position":D=G.split(",");
t=D[0];l.Pe=Number.parseInt(t,10);2==D.length&&(q=D[1].trim());break;case "align":switch(G){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Ig=100,v||(v="end"));if(!t)switch(l.textAlign){case 0:l.Pe=0;break;case 1:l.Pe=100;break;default:l.Pe=50}t=0;switch(v){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(q){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Wf=0>t||8<t?7:t;q=l;f=f.substring(B4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=l4(m,n,5,t),n=new m3(m,n,5,k.id,q,!1,g.Wb(f)?void 0:f),c.push(k),c.push(n),g.B(k,n),k.o.push(n);else for(v=q.split(Dpa),1==v.length?(q=5,t=l4(m,n,q,t)):(z=q=6,t=Object.assign({Ql:32},t),t=new n3(m,n,z,"_"+o3++,t)),c.push(t),z=m,l=0;l<v.length;l++)C=v[l],0==l%2?(D=g.W_("<html>"+C+"</html>"),D.getElementsByTagName("parsererror").length?
(G=D.createElement("span"),G.appendChild(D.createTextNode(C))):G=D.firstChild,j4(this,z,n-(z-m),q,t,0<l,G,f,c)):z=k4(C)+k}B4.lastIndex=0}}return c};
var Cpa=/^NOTE/,Bpa=/(?:\r\n|\r|\n){2,}/,B4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Dpa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(m4,g.A);m4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
m4.prototype.reset=function(){this.o&&this.o.reset()};
m4.prototype.Y=function(){this.clear();g.A.prototype.Y.call(this)};g.r(p4,g.FQ);g.h=p4.prototype;g.h.Y=function(){if(this.B||this.H){var a=this.U.app.B;a&&a.sj()}else A4(this,!1);g.FQ.prototype.Y.call(this)};
g.h.load=function(){g.FQ.prototype.load.call(this);var a=!g.S(this.w.experiments,"web_player_captions_track_list_changed_killswitch");this.D=this.player.getAudioTrack();if(this.u)this.o&&(this.Z.clear(),this.B?v4(this,!0):3!=this.player.getPresentingPlayerType()&&this.u.Mq(this.o,"srv3",(0,g.x)(this.bM,this)),!a||this.B||this.H||u4(this)||this.player.ma("captionschanged",Z2(this.o))),a||(this.o&&!u4(this)?this.player.ma("captionschanged",Z2(this.o)):this.player.ma("onCaptionsTrackListChanged"));else{var b;
this.la?b=new i3(this.T.ka,this.player):this.xa?b=new d3(this.w,this.T,this.player.getAudioTrack()):b=new l3(this.T.rj,this.T.videoId,this.T.captionsLanguagePreference||this.w.captionsLanguagePreference||g.zC(this.T,"yt:cc_default_lang")||this.w.fc,this.T.jp,this.w);this.u=b;g.B(this,this.u);b.Nq((0,g.x)(this.aM,this))}};
g.h.unload=function(){this.B&&this.o?v4(this,!1):(this.ra&&g.Vm(this.ra),g.ZR(this.player.app,"captions",void 0),this.J=[],this.u&&this.u.Jg(),this.Z.clear(),this.G&&g.lL(this.player,this.G),this.mt());g.FQ.prototype.unload.call(this);var a=g.W(this.player.app);a&&g.fI(a.B);this.player.ma("captionschanged",{})};
g.h.create=function(){(this.ga?this.B||this.H:r4(this)||q4(this))&&this.load()};
g.h.aM=function(){var a;this.R||q4(this)?a=t4(this,this.R):r4(this)&&(a=s4(this));if(this.B||this.H){for(var b=a3(this.u.u,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Az(e),srclang:$2(e),id:e.toString()};this.H||(f.src=this.u.Jj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Kd("TRACK",f))}a=this.U.app.B;a.nj(c);c=a.Za();this.oa&&this.P.M(c.textTracks,"change",this.cM)}else!this.o&&a&&x4(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.cM=function(){for(var a=this.U.app.B.Za().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=a3(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.o:null)!=b&&x4(this,b,!0)};
g.h.KN=function(){!this.o&&this.B||this.unload()};
g.h.bM=function(a,b,c,d){if(a){this.u.Gz()&&(this.J=[],g.ZR(this.U.app,"captions",void 0),this.ba.hi(),this.Z.reset());var e=this.Z;c=c||0;d=d||0;if("string"!==typeof a){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Su(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!f4(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<
m&&365>m){n=a[k++];var q=a[k++],t=a[k++];m=((m&7)<<18|(n&63)<<12|(q&63)<<6|t&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],q=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|q&63)}a=f.join("")}}if(a)try{if("string"!==typeof a){var v=a,z=c,C=d;if(!f4(v))throw Error("Invalid binary caption track data");e.o||(e.o=new d4(C,b));var D=e.o.A(v,z)}else{if("WEBVTT"==a.substring(0,6)){b=a;z=c;e.o||(e.o=new i4);var G=e.o.A(b,z);.01>Math.random()&&
g.ko(Error("Deprecated subtitles format in web player: WebVTT"));v=G}else b:{G=a;z=g.W_(G);if(!z||!z.firstChild){var K=Error("Invalid caption track data");K.params=G;throw K;}if("timedtext"==z.firstChild.tagName){if(3==parseInt(z.firstChild.getAttribute("format"),10)){if(!e.o){G={};if(C=$2(b))G.lang=C,zpa.test(C)&&(G.te=1);e.o=new R3(G,e.u)}v=e.o.A(z,c);break b}var F=Error("Unsupported subtitles format in web player (Format2)");F.params=G;throw F;}if("transcript"==z.firstChild.tagName){var M=Error("Unsupported subtitles format in web player (Format1)");
M.params=G;throw M;}var ka=Error("Invalid caption track data");ka.params=G;throw ka;}D=v}var na=D}catch(Ha){g.O(Ha),e.clear(),na=[]}else na=[];g.lL(this.player,na);!this.R||this.H||u4(this)||g.Xx(this.w)||g.Yx(this.w)||(g.Vm(this.ra),na=p3({Wf:0,Pe:5,Ig:5,Jk:2,textAlign:0,te:0,lang:"tr"}),this.V=[na],e=["Ayarlar i\u00e7in "," simgesini t\u0131klay\u0131n"],this.fa||(D=new g.kK(g.qN()),g.B(this,D),this.fa=D.element),D=na.end-na.start,(b=g.Az(this.o))&&this.V.push(new m3(na.start,D,0,na.id,b)),this.V.push(new m3(na.start,
D,0,na.id,e[0]),new m3(na.start,D,0,na.id,this.fa,!0),new m3(na.start,D,0,na.id,e[1],!0)),g.lL(this.player,this.V),g.Tm(this.ra));!this.R||this.H||u4(this)||(w4(this,"module-enabled",!0),this.D&&(this.D.o=this.o),(na=g.W(this.player.app))&&g.fI(na.B));this.R=!1}};
g.h.yF=function(a){this.J.push(a);this.ba.hi()};
g.h.zF=function(a){g.bb(this.J,a);this.u instanceof i3&&this.u.C&&g.wU(this.player.app,[a],void 0);this.ba.hi()};
g.h.PM=function(a){if(a instanceof n3){var b=this.L[a.id];b&&b.A!=a&&(b.dispose(),delete this.L[a.id],b=null);b||(b=ypa(this,a))&&(this.L[a.id]=b)}else b=a.windowId,this.da[b]||(this.da[b]=[]),this.da[b].push(a)};
g.h.WM=function(){z4(this,this.V);this.V=null};
g.h.cB=function(){this.ba.stop();g.Xb(this.da);this.J.sort(g.kF);var a=this.J;if(this.G){var b=(0,g.Rd)(a,function(c){return-1==this.G.indexOf(c)},this);
b.length&&(a=b)}(0,g.y)(a,this.PM,this);g.Ib(this.L,function(c,d){this.da[d]?(c.element.parentNode||g.pL(this.player,c.element,4),c.Hh(this.da[d])):(c.dispose(),delete this.L[d])},this)};
g.h.bN=function(){n4(this,{},!0);g.S(this.w.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.ma("captionssettingschanged")};
g.h.CD=function(){var a=y4.vb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Oe?3:a.bold?1:a.Oe?2:0,textOpacity:a.textOpacity,windowColor:y4.windowColor,windowOpacity:y4.windowOpacity};var b=o4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.hB=function(a,b){var c={};g.Pa(c,o4(this,"display-settings"));g.Pa(c,a);n4(this,c,b);this.player.ma("captionssettingschanged")};
g.h.mt=function(){!this.B&&this.loaded&&(g.Ib(this.L,function(a,b){a.dispose();delete this.L[b]},this),this.cB())};
g.h.yc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.kd(b,-2,4);this.hB({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&x4(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.w.wb&&w4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.La(b))break;if(g.Wb(b)){x4(this,null,!0);break}for(var d=a3(this.u.u,!0),e=0;e<d.length;e++){var f=d[e];f.u!=b.languageCode||c&&f.w!=b.languageName||(c=b.translationLanguage?ipa(f,b.translationLanguage):
f)}!c||c==this.o&&this.loaded||x4(this,c,!0)}else return this.loaded&&this.o&&!u4(this)?Z2(this.o):{};return"";case "tracklist":return this.u?(0,g.H)(a3(this.u.u,!(!b||!b.includeAsr)),function(k){return Z2(k)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.B||void 0==b||A4(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.w.wb&&a.push("stickyLoading");return a};
g.h.xF=function(){var a=this.o;return a?{cc:a.C}:{}};
g.h.CN=function(){this.loaded&&this.o&&!u4(this)?(w4(this,"module-enabled",!1),this.unload(),r4(this,!0)&&x4(this,s4(this),!1)):x4(this,u4(this)||!this.o?t4(this,!0):this.o,!0)};
g.h.XI=function(){var a=u4(this);r4(this,a)?x4(this,this.player.getAudioTrack().gm,!1):this.T.captionTracks.length&&(this.loaded&&this.unload(),(this.ga?this.B||this.H:r4(this)||q4(this))&&(a?x4(this,t4(this),!1):this.load()))};g.VQ.captions=p4;})(_yt_player);
